import Foundation

enum SampleData {
    static let items: [CatalogItem] = [
        CatalogItem(
            id: "zara-trench",
            name: "Cropped Trench Coat",
            brand: "Zara",
            category: "Outerwear",
            price: 89.90,
            measurements: [
                "XS": "Bust 33-34, Waist 26-27, Shoulder 15",
                "S": "Bust 35-36, Waist 28-29, Shoulder 15.5",
                "M": "Bust 37-38, Waist 30-31, Shoulder 16",
                "L": "Bust 39-41, Waist 32-34, Shoulder 16.5",
            ],
            sizingNote: "Cropped at waist — size up for layering",
            fabric: "Cotton-blend gabardine with belt",
            accentHex: "#C4A67A",
            badge: "Hero Pick",
            source: .main,
            summary: "Editorial outerwear with a structured waist and clean shoulder line.",
            productURL: "https://www.zara.com/"
        ),
        CatalogItem(
            id: "reformation-cary",
            name: "Studded Cary Jean",
            brand: "Reformation",
            category: "Bottoms",
            price: 198,
            measurements: [
                "24": "Waist 24, Hip 35, Inseam 31",
                "25": "Waist 25, Hip 36, Inseam 31",
                "26": "Waist 26, Hip 37, Inseam 31.5",
                "27": "Waist 27, Hip 38, Inseam 31.5",
                "28": "Waist 28, Hip 39, Inseam 32",
            ],
            sizingNote: "Slouchy wide-leg — size for waist",
            fabric: "Rigid organic cotton denim with stud detail",
            accentHex: "#4A5A70",
            badge: "Best Denim",
            source: .main,
            summary: "A relaxed premium denim fit that rewards confident waist sizing.",
            productURL: "https://www.thereformation.com/"
        ),
        CatalogItem(
            id: "skims-bodysuit",
            name: "Fits Everybody Bodysuit",
            brand: "SKIMS",
            category: "Tops",
            price: 62,
            measurements: [
                "XXS": "Bust 28-30, Waist 20-22",
                "XS": "Bust 30-32, Waist 22-24",
                "S": "Bust 32-34, Waist 25-27",
                "M": "Bust 34-36, Waist 27-29",
                "L": "Bust 37-39, Waist 30-32",
            ],
            sizingNote: "Stretchy — order your usual size",
            fabric: "Ultra-stretch smoothing jersey",
            accentHex: "#C4A882",
            badge: "High Confidence",
            source: .main,
            summary: "A smoothing essential that adapts well to body changes.",
            productURL: "https://skims.com/"
        ),
        CatalogItem(
            id: "abercrombie-sloane",
            name: "Sloane Tailored Pant",
            brand: "Abercrombie",
            category: "Bottoms",
            price: 90,
            measurements: [
                "25": "Waist 25, Hip 35.5, Inseam 27",
                "26": "Waist 26, Hip 36.5, Inseam 27",
                "27": "Waist 27, Hip 37.5, Inseam 27.5",
                "28": "Waist 28, Hip 38.5, Inseam 27.5",
            ],
            sizingNote: "True to size — available in short, regular, long",
            fabric: "Ponte knit with stretch",
            accentHex: "#2D2D2D",
            badge: "Office Favorite",
            source: .main,
            summary: "Tailored structure with enough give for all-day wear.",
            productURL: "https://www.abercrombie.com/"
        ),
        CatalogItem(
            id: "cos-knit",
            name: "Soft Sculpt Knit Dress",
            brand: "COS",
            category: "Dresses",
            price: 150,
            measurements: [
                "XS": "Bust 31-32, Waist 24-25, Hip 34-35",
                "S": "Bust 33-34, Waist 26-27, Hip 36-37",
                "M": "Bust 35-36, Waist 28-29, Hip 38-39",
                "L": "Bust 37-39, Waist 30-32, Hip 40-42",
            ],
            sizingNote: "Column silhouette — true to size",
            fabric: "Compact viscose knit",
            accentHex: "#8A6F5B",
            badge: nil,
            source: .main,
            summary: "Minimalist dress with a long clean line and subtle waist definition.",
            productURL: "https://www.cos.com/"
        ),
        CatalogItem(
            id: "studio-shirt",
            name: "Classic White Shirt",
            brand: "FitAR Collection",
            category: "Tops",
            price: 15.60,
            measurements: [
                "S": "Bust 33-34, Waist 26-27, Shoulder 14.5",
                "M": "Bust 35-36, Waist 28-29, Shoulder 15",
                "L": "Bust 37-38, Waist 30-31, Shoulder 15.5",
                "XL": "Bust 39-41, Waist 32-34, Shoulder 16",
            ],
            sizingNote: "Structured studio sample — true to size",
            fabric: "Imported from the IDM-VTON starter catalogue",
            accentHex: "#E8E0D6",
            badge: "Studio Drop",
            source: .studio,
            summary: "A crisp prototype pulled from the imported IDM-VTON catalog.",
            productURL: nil
        ),
        CatalogItem(
            id: "studio-jacket",
            name: "Blue Denim Jacket",
            brand: "FitAR Collection",
            category: "Outerwear",
            price: 30.10,
            measurements: [
                "S": "Bust 33-34, Waist 26-27, Shoulder 14.5",
                "M": "Bust 35-36, Waist 28-29, Shoulder 15",
                "L": "Bust 37-38, Waist 30-31, Shoulder 15.5",
                "XL": "Bust 39-41, Waist 32-34, Shoulder 16",
            ],
            sizingNote: "Relaxed denim layer — size down for a sharper line",
            fabric: "Imported from the IDM-VTON starter catalogue",
            accentHex: "#6A84A7",
            badge: "Studio Drop",
            source: .studio,
            summary: "A wearable test piece for try-on mode and fit-preview workflows.",
            productURL: nil
        ),
        CatalogItem(
            id: "studio-blazer",
            name: "Black Formal Blazer",
            brand: "FitAR Collection",
            category: "Outerwear",
            price: 48.20,
            measurements: [
                "S": "Bust 33-34, Waist 26-27, Shoulder 14.5",
                "M": "Bust 35-36, Waist 28-29, Shoulder 15",
                "L": "Bust 37-38, Waist 30-31, Shoulder 15.5",
                "XL": "Bust 39-41, Waist 32-34, Shoulder 16",
                "XXL": "Bust 42-44, Waist 35-37, Shoulder 16.5",
            ],
            sizingNote: "Structured studio sample — choose slim for a sharper shoulder line",
            fabric: "Imported from the IDM-VTON starter catalogue",
            accentHex: "#2A2B2E",
            badge: "Studio Tailoring",
            source: .studio,
            summary: "A formal prototype that works especially well with the slim fit bias.",
            productURL: nil
        ),
        CatalogItem(
            id: "studio-chinos",
            name: "Khaki Chinos",
            brand: "FitAR Collection",
            category: "Bottoms",
            price: 18.10,
            measurements: [
                "30": "Waist 30, Hip 39, Inseam 30.5",
                "32": "Waist 32, Hip 41, Inseam 31",
                "34": "Waist 34, Hip 43, Inseam 31.5",
                "36": "Waist 36, Hip 45, Inseam 32",
            ],
            sizingNote: "Comfort-first studio fit — regular or relaxed preference works best",
            fabric: "Imported from the IDM-VTON starter catalogue",
            accentHex: "#B79B6B",
            badge: "Studio Drop",
            source: .studio,
            summary: "A flexible starter bottom for the virtual try-on studio catalog.",
            productURL: nil
        ),
    ]
}

